# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dewseph
# "service" is the name of this project. This will also be added to your AWS resource names.
service: SpeedMonitorApi
frameworkVersion: "4"
useDotenv: true
plugins:
  - serverless-offline
 

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors: true


functions:
  hello:
    handler: handler.hello
    environment:
      TABLE_NAME: ${env:TABLE_NAME}
      SECRET_KEY: ${env:SECRET_KEY}
      ACCESS_KEY: ${env:ACCESS_KEY}
      API_KEYS: ${env:API_KEYS}
    events:
      - httpApi:
          path: /api/v1/ping
          method: get
  saveDataPoints:
    handler: handler.saveSpeedDataPoint
    environment:
      TABLE_NAME: ${env:TABLE_NAME}
      SECRET_KEY: ${env:SECRET_KEY}
      ACCESS_KEY: ${env:ACCESS_KEY}
      JWT_SECRET: ${env:JWT_SECRET}
      API_KEYS: ${env:API_KEYS}

    events:
      - httpApi:
          path: /api/v1/speed
          method: post
  getDataPoints:
    handler: handler.getSpeedDataPoints
    environment:
      TABLE_NAME: ${env:TABLE_NAME}
      SECRET_KEY: ${env:SECRET_KEY}
      ACCESS_KEY: ${env:ACCESS_KEY}
      JWT_SECRET: ${env:JWT_SECRET}
      API_KEYS: ${env:API_KEYS}
    events:
      - httpApi:
          path: /api/v1/speed
          method: get
  getToken: 
    handler: handler.getToken
    environment:
      JWT_SECRET: ${env:JWT_SECRET}
      API_KEYS: ${env:API_KEYS}
    events:
      - httpApi:
          path: /api/v1/token
          method: post
